### ISSUE TITLE
Stole Map - Arizona

### ISSUE THREAD

**Issue by resepignev** [mchostco/Maps#2]
Good day,
I saw that the minehut network has a particular map in their maps repository called "Arizona". 
The map was built and submitted by a mapdev on another network. After checking the forums of the minehut network, I can't seem to find a thread about submitting it, so I assume the owner of this network and repository is responsible for adding the map to this network.
I would like to request to remove the map since it's used without consent of the author or the network where the map was originally submitted to.

I hope you agree with removing the map or consequences will most likely follow, maybe even legal consequences.

**Comment by lukechatton** [comment]
This map has been out of the rotation for quite a long time. I may change my mind later, so I won't remove it. 

You can find my personal info here and over at twitter.com/luukelol for any legal action you wanna take lmao.

**Comment by lukechatton** [comment]
Removed.
