### ISSUE TITLE
Request of removal.

### ISSUE THREAD

**Issue by mitchiiii** [mchostco/Maps#4]
Luke, I'm unsure if you haven't seen my messages or are just straight up ignoring them, so I'll just repeat myself here for everyone to see.
This service, being MineHut, is using four of my maps without permission or informing me of their use. I'm not sure where you got the content from, but if it was from any of my sites you would be aware that services that make a profit are not permitted to use this content without explicit permission from the author, being myself. I would greatly appreciate it if you *completely* remove this content from your service, being this repository, the server rotations and anywhere else this content may have been used.
Thanks.

This issue is regarding the use of Forsaken Fort, Pirate's Isle, Rooted Frontier and Frost Bound.

**Comment by lukechatton** [comment]
Removed! Sorry for the delay!

**Comment by mitchiiii** [comment]
Thank you. :+1:
